function [status,temperature,acceleration_y,acceleration_x,humidity,pressure,v_pd,v_cc,id,acceleration_z,timestamp] = importfile1(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   [STATUS,TEMPERATURE,ACCELERATION_Y,ACCELERATION_X,HUMIDITY,PRESSURE,V_PD,V_CC,ID,ACCELERATION_Z,TIMESTAMP]
%   = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [STATUS,TEMPERATURE,ACCELERATION_Y,ACCELERATION_X,HUMIDITY,PRESSURE,V_PD,V_CC,ID,ACCELERATION_Z,TIMESTAMP]
%   = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [status,temperature,acceleration_y,acceleration_x,humidity,pressure,v_pd,v_cc,id,acceleration_z,timestamp]
%   = importfile1('stream_G2x5VRRgqguX5nmAgnoX.csv',2, 2985);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/10/30 20:04:07

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
status = dataArray{:, 1};
temperature = dataArray{:, 2};
acceleration_y = dataArray{:, 3};
acceleration_x = dataArray{:, 4};
humidity = dataArray{:, 5};
pressure = dataArray{:, 6};
v_pd = dataArray{:, 7};
v_cc = dataArray{:, 8};
id = dataArray{:, 9};
acceleration_z = dataArray{:, 10};
timestamp = dataArray{:, 11};

